name: PHPStan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/composite-actions/setup

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse .
