name: Tests coverage badge
on:
  push:
    branches:
      - tests-coverage

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/composite-actions/setup
        with:
          php-version: "7.4"

      - name: Run Unit Tests
        run: vendor/bin/phpunit

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: tests/coverage/xml/clover.xml
          coverage_badge_path: tests/coverage/badge.svg

      - name: Push to branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch -c coverage-badges-${{ github.sha }}
          git add tests/coverage/xml/clover.xml
          git add tests/coverage/badge.svg
          git commit -m "Update coverage badge"
          git push --set-upstream origin coverage-badges-${{ github.sha }}
